# Use root/root as user/password credentials
version: '3.1'
  ​
services:
  ​
simple-crud-db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
  ports:
    #exposed on 3600
    - 3600:3306